<!DOCTYPE HTML>
<html>
<head>

    <title>RentNGo</title>
    <link rel="stylesheet" type="text/css" href="css/reset.css">
</head>
 
<body>
   <header>
    <div class="wrapper">
        <h1>Rent n' Go<span class="color">.</span></h1>
        <nav>
            <ul>
                <li><a href="index.php">Home</a></li>
                <li><a href="About.php">About </a></li>
                <li><a href="#">Contact</a></li>
                <li><a href="#">Policy</a></li>
                <li><a href="#">FAQ</a></li>
                <li><a href="#">Sign In</a></li>
            </ul>
        </nav>
    </div>
</header>
 <div id="about">
<div class="wrapper">
                <h3>Term of use</h3>
				<a>
				</class>
				This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
				</a><br><br>
				<a>
				This document sets out the Terms and Conditions for renting vehicle from Rent N Go Motor Company Pvt. Ltd.,
				a company incorporated under the companies Act.......with CIN......... 
				This document is an agreement between Rent N Go Motor Company Pvt. Ltd. 
				(herein after referred to as Rent N Go) and Users (herein after referred to as User) 
				and is legally binding between the User and the Rent N Go . 
				This document will be effective upon your acceptance of the same and 
				will govern the relationship between User and Rent N Go 
				for the use of the vehicles.
				</a><br><br>
				<a>
				For the purpose of these Terms and conditions, wherever the context so require, the term :<br><br>
				<strong><b>i.Vehicle</strong></b> shall mean the vehicle rented by the User from company along with all its parts including but not limited to, tires (including spare tire), tools, vehicle documents,
				accessories and equipment.
				<br><strong><b>ii. User</strong></b> shall mean the guest users or registered users, who are availing the vehicle from the company
			  <br></a>
			  <a>
			  Users are requested to read the Terms and condition of this agreement carefully 
			  before using or registering on the website or availing services through the website of Rent N 
			  GO. If you do not agree with this Terms and conditions ,
			  please do not use the website or avail any services being offered through website.<br><br></a>
			  
			  <a>
			  Upon accepting the Terms and Conditions as set out herein after , the User agrees and acknowledges that :
			  <br>
			  <br>
			  i. The terms and conditions of services provided by the company has displayed in the website
			  <br>
			  <br>
			  ii. User has read and understood the Terms and Conditions including those relating 
			  to rental of vehicles, payment structure, usage of vehicles, damages, obligation of the users, 
			  Traffic violation and penalties so on.
			  <br>
			  <br>
			  iii. Company reserves the right to change the terms and conditions of this agreement from time to time with the provision of notice 
			  in a timely manner. Notice to the user shall be 
			  considered served when these terms and conditions updated on the website 
			  user viewed those changes when log on to the website, by email to the users
			  registered email ID to the 
			  company.The user agrees that the amended Terms and conditions of this agreement shall be 
			  effective and binding on the date when such change is posted on the website or on the date 
			  indicated in the notice.
              <br>
			  <br>
			  iv. The provision of the vehicle to the user is subject to the acceptance of all the Terms and conditions set out here in. In the event that user does not accept any Terms and conditions as provided herein or as may be amended, user shall not be authorized to use any vehicle provided by the company.
               <br>
			   <br>
			   <br>
			   </a>
			   <a>
			   <strong><b>1. Eligibility to enrol as Users</strong></b></a>
               <br>
			   <br>
			   <a>
			   Any person desirous of enrolling as a user with Rent N GO, Users should possess the following eligible criteria
               <br>
			   <br>
			   </a>
			   
			   <a><li>Such person must be of a sound mind</li>
			  <li> Such person must be minimum of 21 years of age</li>
             <li> Such person must be an Indian Citizen and must possess a Valid Light Motor Vehicle (LMV) 
			 non transport Indian license for minimum of last one year.</li>
           <li> Such person must have a good driving record and should not have been found guilty of any o
			ffence involving moral turpitude or any offence under Motor Vehicles Act for which imprisonment 
			for more than 6 months have been prescribed.</li>
             <li>Such person should not have any previous criminal records 
			 and without any restrictions on driving due to any medical conditions 
			 or any other restrictions imposed under any law .</li></a>
			 <br>
			 <br>
			<a> <strong><b>1. Enrolment Formalities</strong></b></a>
			 <br>
			 <br>
			<a> <li><strong><b>a. For car handover, users shall provide the following documents for verification to the 
			 designated fleet executive</strong></b></a>
			<a><li>Scanned copy of users driving license</li></a>
			<a> <li>Valid ID Proof issued by Government of India.</li></a>
            <br>
			<br>
			<a>
			<strong><b>
		   a. Company reserve the right to refuse the acceptance of any person as a user without assigning any reason thereto.
            <br>b. If a user is unable to verify with their identity, the booking shall be considered void.
             <br>c. The possession of vehicle will not be granted to user in case he fails to meet the above requirements.
		</strong></b>
		</a>
		<br>
		<br>
		<strong><b><a>
		1. Prohibited use of Indus GO Vehicles</strong></b></a>
		<br>
		<br>
		<a>
		Rent N GO vehicles are solely for the purpose of personal use.
		Users shall not use the vehicle for the following purpose and violation of these 
		terms will terminate the agreement res judicata.
		User shall liable to Indus GO for all penalties, fines, legal expenses, fees and cost that may incur.</a>
		<br>
		<br>
	<a>	
Vehicle cannot be used for the primary business purpose of transporting people / property for monetary 
gain or operating a taxi Service Vehicle cannot be used for races, contest, exhibition, 
test Vehicles cannot be used for the purpose of towing, pushing, or propelling any trailer 
or any other Vehicle or object By any person who is under the influence of (i) alcohol or (ii) 
any drug or medication or any mind altering substance which can impair the users ability
 to drive and under the effects of which the operation of a vehicle is prohibited or not recommended; 
 Users will not be allowed to carry that could be charges as a crime including the transportation of a
 controlled substances or contraband , weapons or any sharp or inflammable object which may cause damage 
 to the vehicle or endanger human life. Any item/object whose possession has been deemed illegal by the 
 Indian Penal Code. Any item or object which compromises the stability, safety or performance of the
 vehicle and/or the passengers. Rent N GO vehicles can be used only in the Republic of India . 
 Use of the vehicles is subject to the laws of India. 
The vehicle cannot be driven in areas where entry is prohibited by the central or state government.</a>
<a>
<br>
<br>
A Rent N GO Vehicle cannot be taken inside Leh and Ladakh region. 
Carrying more than the authorized number of persons (equal to the number of seat-belts) 
in the Rent N GO Vehicle. For the purpose of commission of any crime or other illegal 
or unlawful activity; In an imprudent, negligent, abusive manner or for any abnormal 
use of the Rent N GO Vehicle; By any person who has provided Rent N GO with false information
 (including, without limitation, any personal information such as name, age, or address) or
 whose representations are determined to be false Driving while using a mobile phone or any 
 other mobile communication device in any manner whatsoever, including while sending an SMS,
 emailing, using a cell phone with or without a hands-free device, otherwise using a mobile 
 communication device or engaging in similar activities that may be prohibited under Applicable Laws; 
 For the purpose of transportation of any goods including any flammable, Poisonous, or otherwise hazardous
 substances; For the purpose of transporting objects that could – due to their size, shape, or weight – 
 adversely impact the vehicles handling safety or that could damage the interior of the Rent N GO Vehicle
 or, by virtue of such object/s protruding outside, affect the safety of vehicles driving in the vicinity 
 of the Rent N GO Vehicle. Use of tobacco, drugs and/or psychotropic substances inside Indus GO Vehicles is
 absolutely prohibited. Users are subject to payment of penalties if evidence of smoking, chewing, or dipping 
 is found in Rent N GO Vehicle. Burning any substance including tobacco, incense etc. 
 inside Indus GO Vehicles is absolutely prohibited. Animals are prohibited in Rent N GO Vehicles. 
 Users are subject to payment of penalties in the event it is determined that the Rent N GO Vehicles have 
 been used for transportation of animals. Any kind of activity by any person which will affect the normal 
 conditions of the vehicle</a>
 <a>
<br>
<br>
<strong></b>1.Booking of Rent N GO Vehicles</strong></b> Rent N GO vehicles will be available for use 24*7 including holidays with the exception of the vehicle having gone for routine/ ad hoc maintenance/repair.
<br></a>
<a>
All bookings have to be made solely by the registered user themselves via our Website<br>
<br>
Users can select the Rent N GO Vehicle as per their requirements
<br>
Users should provide the start and end date and time, indicating the duration for which the Rent N GO vehicle will be required for use by the User
<br>
<br>
<br>
</a>
<a>
<strong><b> Vehicle Condition</strong></b>
<br>
Prior to taking possession, it is the User's responsibility to inspect the vehicle carefully. 
In the event of any damages or malfunction, the user should inform company immediately.
Users shall be permitted to test drive the Rent N GO Vehicle to ensure that there is no damage or abnormality encountered in the operation of the vehicle. 
In case such an abnormality or damage is found, User shall be required to intimate Rent N GO of any such
 damage or abnormality encountered on 
the vehicle or in the operation of the vehicle prior to taking possession of such vehicle.<br>
User is requested to report to Rent N Go  immediately any condition that impairs the driving functionality and/or safety of the vehicle, such as performance changes, inappropriate noises, smells or driving feel, including but not limited to warning lamps, indicators, poor driving feel or external or internal damage that renders the vehicle unsafe, including but not limited to, missing or inoperable signal or driving lighting, 
broken or missing rear-view mirrors and windshield glass etc. </a>
<a>
<br>
<br>
<strong><b>Damage to Vehicles</strong></b>
<br>
<br>
If the vehicle is damaged, User shall responsible for all such loss and damages and shall pay to the Indus GO for all loss of or damage
 to the car regardless of cause, or who, or what caused it.<br>
 In the event of damages, customer liability will be limited to a maximum of Rs 30,000. 
 The customer will need to pay damage fee equivalent to the repair cost (as estimated by an authorized dealership)
 and downtime losses, up to a maximum of Rs 5000. This is independent of the nature and terms of the
 insurance cover that Rent N GO will have on the cars.
The maximum liability policy is intended to benefit and protect the responsible user.
In situations of irresponsible or unsafe or negligent usage,
 there could be discretionary exceptions to this policy, whereby the user could be 
 liable for all damages irrespective of whether or not Rent N  GO is able to claim insurance in such cases.
 Such situation include, but are not limited to:<br><br><br></a>
 <a>
 
<li>When the User is not in compliance with the laws and/or with terms of the Rent N GO User Agreement</li>
<li>When the User is found to be under the influence of alcohol/narcotics while Driving</li>
<li>When the User is over-speeding (i.e., above 90 Kms/Hr)</li>
<li>When the User is in violation of traffic rules or of the Motor Vehicles Act</li>
<li>When the person driving the vehicle at the time of the incident is found to be different than the 
one who made the booking</li>
<li>When the vehicle workshop and/or insurance company deem the damage to be consequential in nature . 
Consequential damage occurs when the user continues driving the vehicle even when it is performing abnormally</li>
<li>When the number of people in the car at the time of the incident exceed the standard seating capacity of the car</li>
<li>When the incident happened in a state for which the user failed to pay the inter-state tax while entering the state</li>
<li>When there is misrepresentation of information in the driving license and ID proof details shared by the user</li>
<li>Where there is clear evidence of extremely rash and negligent driving on the user’s part</li></a>




				